---
- name: get cme
  git:
    repo: https://github.com/byt3bl33d3r/CrackMapExec
    dest: /opt/cme
    update: yes
    track_submodules: yes
    recursive: yes

- name: install cme
  shell: python setup.py install
  args:
    chdir: /opt/cme

- name: get xfltreat
  git:
    repo: https://github.com/earthquake/XFLTReaT
    dest: /opt/xfltreat
    version: next-version
    update: yes

- name: install python2 dependences for xfltreat
  pip:
    requirements: requirements.txt
  args:
    chdir: /opt/xfltreat

- name: enable ip forwarding for xfltreat
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: configure iptables for xfltreat
  shell: iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

- name: get proxychains-ng
  git:
    repo: https://github.com/rofl0r/proxychains-ng
    dest: /opt/proxychains-ng
    update: yes

- name: install proxychains-ng
  shell: ./configure --prefix=/usr --sysconfdir=/etc && make && make install && make install-config
  args:
    chdir: /opt/proxychains-ng
