---
- name: get msf installer
  get_url:
    url: https://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run
    dest: /tmp/msfinstall
    mode: 0755

- name: get beef (requires `gem install bundler && bundle install`)
  git:
    repo: https://github.com/beefproject/beef
    dest: /opt/beef
    update: yes

- name: get ikeforce
  git:
    repo: https://github.com/SpiderLabs/ikeforce
    dest: /opt/ikeforce
    update: yes

- name: get impacket
  git:
    repo: https://github.com/CoreSecurity/impacket
    dest: /opt/impacket
    update: yes

- name: install impacket
  shell: python setup.py install
  args:
    chdir: /opt/impacket

- name: get responder
  git:
    repo: https://github.com/lgandx/Responder
    dest: /opt/responder
    update: yes

- name: get routersploit
  git:
    repo: https://github.com/reverse-shell/routersploit
    dest: /opt/routersploit
    update: yes

- name: install routersploit
  pip:
    requirements: requirements.txt
  args:
    chdir: /opt/routersploit

- name: get set
  git:
    repo: https://github.com/trustedsec/social-engineer-toolkit
    dest: /opt/set
    update: yes

- name: install set
  shell: python setup.py install
  args:
    chdir: /opt/set

- name: get sqlmap
  git:
    repo: https://github.com/sqlmapproject/sqlmap
    dest: /opt/sqlmap
    update: yes
