---
- name: get oh-my-zsh
  shell: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

- name: get powerline for zsh
  git:
    repo: https://github.com/bhilburn/powerlevel9k
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
    update: yes

- name: get fonts
  git:
    repo: https://github.com/ryanoasis/nerd-fonts
    dest: /tmp/nerd-fonts

- name: install fonts
  shell: ./install.sh DroidSansMono
  ignore_errors: yes
  args:
    chdir: /tmp/nerd-fonts

- name: cleanup font installer
  file:
    path: /tmp/nerd-fonts
    state: absent

- name: get tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: configure tmux
  template:
    src: tmux.conf.template
    dest: ~/.tmux.conf

- name: set .vimrc
  template:
    src: vimrc.template
    dest: ~/.vimrc

- name: set .zshrc
  template:
    src: zshrc.template
    dest: ~/.zshrc

- name: enable root gdm3 gui login (1/2)
  replace:
    path: /etc/gdm3/daemon.conf
    regexp: '\[security\]'
    replace: '[security]\nAllowRoot = true'
    backup: yes

- name: enable root gdm3 gui login (2/2)
  replace:
    path: /etc/pam.d/gdm-password
    regexp: 'auth\s+required\s+pam_succeed_if.so user != root quiet_success'
    replace: '# auth  required  pam_succeed_if.so user != root quiet_success'
    backup: yes

- name: acquire nerdy desktop background
  get_url:
    url: https://goo.gl/qXsyq6
    dest: /root/Pictures/grey_empire_background.png
    mode: 0644

- name: set destkop login background
  shell: update-alternatives --install /usr/share/images/desktop-base/login-background.svg desktop-login-background /root/Pictures/grey_empire_background.png 50 && update-alternatives --set desktop-login-background /root/Pictures/grey_empire_background.png

- name: set destkop background
  shell: update-alternatives --install /usr/share/images/desktop-base/desktop-background.svg desktop-background /root/Pictures/grey_empire_background.png 50 && update-alternatives --set desktop-background /root/Pictures/grey_empire_background.png
